export const carBrandsModels = [
  {
    brand: "Audi",
    models: [
      "A1",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q3",
      "Q5",
      "Q7",
      "Q8",
      "TT",
    ],
  },
  {
    brand: "BMW",
    models: [
      "1 Series",
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "6 Series",
      "7 Series",
      "8 Series",
      "X1",
      "X3",
      "X5",
      "X6",
      "X7",
      "Z4",
    ],
  },
  {
    brand: "Mercedes-Benz",
    models: [
      "A-Class",
      "B-Class",
      "C-Class",
      "CLA",
      "CLS",
      "E-Class",
      "G-Class",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLS",
      "S-Class",
      "V-Class",
    ],
  },
  {
    brand: "Volkswagen",
    models: [
      "Beetle",
      "Caddy",
      "Golf",
      "Jetta",
      "Passat",
      "Polo",
      "Sharan",
      "T-Cross",
      "Tiguan",
      "Touareg",
      "Touran",
    ],
  },
  {
    brand: "Toyota",
    models: [
      "Auris",
      "Avensis",
      "Camry",
      "Corolla",
      "C-HR",
      "Fortuner",
      "Highlander",
      "Hilux",
      "Land Cruiser",
      "Prado",
      "RAV4",
      "Yaris",
    ],
  },
  {
    brand: "Honda",
    models: [
      "Accord",
      "Civic",
      "CR-V",
      "Fit",
      "HR-V",
      "Insight",
      "Jazz",
      "Odyssey",
      "Pilot",
    ],
  },
  {
    brand: "Hyundai",
    models: [
      "Accent",
      "Creta",
      "Elantra",
      "Getz",
      "H-1",
      "i20",
      "i30",
      "Palisade",
      "Santa Fe",
      "Solaris",
      "Sonata",
      "Tucson",
    ],
  },
  {
    brand: "Kia",
    models: [
      "Carnival",
      "Ceed",
      "Cerato",
      "K5",
      "Mohave",
      "Optima",
      "Picanto",
      "Rio",
      "Seltos",
      "Sorento",
      "Soul",
      "Sportage",
    ],
  },
  {
    brand: "Nissan",
    models: [
      "Almera",
      "Altima",
      "Juke",
      "Maxima",
      "Micra",
      "Murano",
      "Navara",
      "Note",
      "Pathfinder",
      "Patrol",
      "Qashqai",
      "Teana",
      "Tiida",
      "X-Trail",
    ],
  },
  {
    brand: "Mazda",
    models: [
      "CX-3",
      "CX-5",
      "CX-7",
      "CX-9",
      "Mazda2",
      "Mazda3",
      "Mazda5",
      "Mazda6",
      "MX-5",
    ],
  },
  {
    brand: "Mitsubishi",
    models: [
      "ASX",
      "Colt",
      "Eclipse Cross",
      "Galant",
      "L200",
      "Lancer",
      "Montero",
      "Outlander",
      "Pajero",
    ],
  },
  {
    brand: "Subaru",
    models: [
      "Forester",
      "Impreza",
      "Legacy",
      "Outback",
      "Tribeca",
      "WRX",
      "XV",
    ],
  },
  {
    brand: "Lexus",
    models: ["CT", "ES", "GS", "GX", "IS", "LC", "LS", "LX", "NX", "RX", "UX"],
  },
  {
    brand: "Infiniti",
    models: [
      "EX",
      "FX",
      "G",
      "M",
      "Q30",
      "Q50",
      "Q60",
      "Q70",
      "QX50",
      "QX60",
      "QX70",
      "QX80",
    ],
  },
  {
    brand: "Porsche",
    models: [
      "718 Boxster",
      "718 Cayman",
      "911",
      "Cayenne",
      "Macan",
      "Panamera",
      "Taycan",
    ],
  },
  {
    brand: "Land Rover",
    models: [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
    ],
  },
  {
    brand: "Volvo",
    models: [
      "C30",
      "S40",
      "S60",
      "S80",
      "S90",
      "V40",
      "V60",
      "V90",
      "XC40",
      "XC60",
      "XC70",
      "XC90",
    ],
  },
  {
    brand: "Peugeot",
    models: [
      "107",
      "206",
      "207",
      "208",
      "3008",
      "301",
      "307",
      "308",
      "407",
      "408",
      "508",
      "5008",
      "Partner",
    ],
  },
  {
    brand: "Renault",
    models: [
      "Arkana",
      "Clio",
      "Duster",
      "Fluence",
      "Kangoo",
      "Kaptur",
      "Koleos",
      "Laguna",
      "Logan",
      "Megane",
      "Sandero",
      "Scenic",
      "Symbol",
    ],
  },
  {
    brand: "Skoda",
    models: [
      "Fabia",
      "Kamiq",
      "Karoq",
      "Kodiaq",
      "Octavia",
      "Rapid",
      "Roomster",
      "Superb",
      "Yeti",
    ],
  },
  {
    brand: "Chevrolet",
    models: [
      "Aveo",
      "Camaro",
      "Captiva",
      "Cobalt",
      "Cruze",
      "Epica",
      "Lacetti",
      "Malibu",
      "Orlando",
      "Tahoe",
      "Tracker",
    ],
  },
  {
    brand: "Ford",
    models: [
      "C-Max",
      "EcoSport",
      "Escape",
      "Explorer",
      "Fiesta",
      "Focus",
      "Fusion",
      "Kuga",
      "Mondeo",
      "Mustang",
      "Ranger",
      "S-Max",
      "Transit",
    ],
  },
  {
    brand: "Opel",
    models: [
      "Astra",
      "Corsa",
      "Insignia",
      "Meriva",
      "Mokka",
      "Omega",
      "Vectra",
      "Vivaro",
      "Zafira",
    ],
  },
  {
    brand: "Suzuki",
    models: [
      "Alto",
      "Baleno",
      "Grand Vitara",
      "Ignis",
      "Jimny",
      "Liana",
      "S-Cross",
      "Swift",
      "SX4",
      "Vitara",
    ],
  },
  {
    brand: "Jeep",
    models: [
      "Cherokee",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Liberty",
      "Patriot",
      "Renegade",
      "Wrangler",
    ],
  },
  {
    brand: "Dodge",
    models: ["Caliber", "Challenger", "Charger", "Durango", "Journey", "Ram"],
  },
  {
    brand: "Chrysler",
    models: ["200", "300", "Pacifica", "PT Cruiser", "Voyager"],
  },
  {
    brand: "Cadillac",
    models: [
      "ATS",
      "CT4",
      "CT5",
      "CT6",
      "Escalade",
      "SRX",
      "XT4",
      "XT5",
      "XT6",
    ],
  },
  {
    brand: "Tesla",
    models: ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck"],
  },
  {
    brand: "Jaguar",
    models: ["E-Pace", "F-Pace", "F-Type", "S-Type", "XE", "XF", "XJ"],
  },
  { brand: "Mini", models: ["Clubman", "Cooper", "Countryman", "Paceman"] },
  {
    brand: "Fiat",
    models: [
      "500",
      "Albea",
      "Bravo",
      "Doblo",
      "Ducato",
      "Linea",
      "Panda",
      "Punto",
    ],
  },
  {
    brand: "Citroen",
    models: [
      "Berlingo",
      "C-Elysee",
      "C1",
      "C3",
      "C4",
      "C5",
      "DS3",
      "DS4",
      "Jumper",
      "SpaceTourer",
    ],
  },
  {
    brand: "Seat",
    models: [
      "Alhambra",
      "Altea",
      "Ateca",
      "Cordoba",
      "Ibiza",
      "Leon",
      "Toledo",
    ],
  },
  { brand: "Acura", models: ["ILX", "MDX", "RDX", "RLX", "TLX"] },
  {
    brand: "Alfa Romeo",
    models: ["147", "156", "159", "Brera", "Giulia", "Giulietta", "Stelvio"],
  },
  {
    brand: "Daewoo",
    models: ["Espero", "Gentra", "Lacetti", "Lanos", "Matiz", "Nexia"],
  },
  {
    brand: "Geely",
    models: ["Atlas", "Coolray", "Emgrand", "GC6", "MK", "Monjaro", "Tugella"],
  },
  {
    brand: "Chery",
    models: [
      "Amulet",
      "Arrizo 5",
      "Arrizo 8",
      "Tiggo 2",
      "Tiggo 4",
      "Tiggo 7 Pro",
      "Tiggo 8 Pro",
    ],
  },
  {
    brand: "Haval",
    models: ["Dargo", "F7", "F7x", "H2", "H5", "H6", "Jolion"],
  },
  { brand: "Great Wall", models: ["Hover H3", "Hover H5", "Poer", "Wingle"] },
  { brand: "BYD", models: ["Atto 3", "Dolphin", "Han", "Qin", "Seal", "Song"] },
  {
    brand: "LADA",
    models: ["Granta", "Kalina", "Largus", "Niva", "Priora", "Vesta", "XRAY"],
  },
  { brand: "GAZ", models: ["Sobol", "Volga", "Gazelle"] },
  { brand: "UAZ", models: ["Hunter", "Patriot", "Pickup"] },
];

export const carSearchOptions = carBrandsModels.flatMap(({ brand, models }) => [
  { value: brand, type: "brand" },
  ...models.map((model) => ({ value: `${brand} ${model}`, type: "model" })),
]);
